# -*- coding: utf-8 -*-
"""MusicPlayer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/100foW4BGxNIRXuTqTXOzFXd_VkScODEJ
"""

import tkinter as tk
from tkinter import ttk
import webbrowser
import os
from googleapiclient.discovery import build

# Set up YouTube API
api_key = "YOUR_API_KEY"
youtube = build('youtube', 'v3', developerKey=api_key)

# Set up the GUI
root = tk.Tk()
root.title("YouTube Music Player")

# Create a search entry field
search_string = tk.StringVar()
search_entry = ttk.Entry(root, width=40, textvariable=search_string)
search_entry.pack()

# Create a search button
def search():
    query = search_string.get()
    response = youtube.search().list(
        part="id",
        type="video",
        q=query,
        videoDefinition="high",
        maxResults=1
    ).execute()

    # Get the first video from the search results
    video = response["items"][0]
    video_id = video["id"]["videoId"]
    video_url = f"https://www.youtube.com/watch?v={video_id}"

    # Open the video in the default web browser
    webbrowser.open(video_url)

search_button = ttk.Button(root, text="Search", command=search)
search_button.pack()

# Run the GUI
root.mainloop()